import { TextInputForm, GenerationStatus } from '@/lib/types/infographic';

// Use mock service in MVP stage to avoid actual API calls
export async function generateInfographic(input: TextInputForm): Promise<string> {
  console.log('Mock AI service generating infographic:', input);

  // Simulate processing delay
  await new Promise(resolve => setTimeout(resolve, 3000));

  // Return a mock data URL as the result
  // In the actual implementation, this will be an image generated by the AI service
  return 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjQwMCIgeT0iMzAwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMjQiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiMzMzMiPk1vY2sgSW5mb2dyYXBoaWM6IFt0ZXh0IHRvIGluZm9ncmFwaGljXTwvdGV4dD48L3N2Zz4=';
}

// Status check function
export async function checkGenerationStatus(id: string): Promise<GenerationStatus> {
  // Simulate processing progress
  const progress = Math.random() * 100;

  // Randomly determine status
  let status: 'pending' | 'processing' | 'completed' | 'failed';

  // 添加一个小概率随机失败的可能性（约5%的概率）
  const shouldFail = Math.random() < 0.05;

  if (shouldFail) {
    status = 'failed';
  } else if (progress < 30) {
    status = 'pending';
  } else if (progress < 90) {
    status = 'processing';
  } else {
    status = 'completed';
  }

  // 构建返回值，确保包含所有必要的属性
  const result: GenerationStatus = {
    status,
    progress: Math.min(100, Math.round(progress)),
    ...(status === 'completed'
      ? {
          result:
            'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iODAwIiBoZWlnaHQ9IjYwMCIgZmlsbD0iI2YwZjBmMCIvPjx0ZXh0IHg9IjQwMCIgeT0iMzAwIiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMjQiIHRleHQtYW5jaG9yPSJtaWRkbGUiIGZpbGw9IiMzMzMiPk1vY2sgSW5mb2dyYXBoaWM6IENvbXBsZXRlZDwvdGV4dD48L3N2Zz4=',
        }
      : {}),
    ...(status === 'failed'
      ? {
          error: 'Mock error message for testing',
        }
      : {}),
  };

  return result;
}
